### PR TITLE
CI tester

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 14-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/64016f77863c8c1f0c9753f104afcef5/raw/f321851fc402dbaae8030b523d60e2b766bca0a4/ompi_jenkins.log) | :question: UNKNOWN

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the artefacts will be deleted after 14-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/a038c994cc6b4e05722d226144e34d4d/raw/82729c171219fa40e01321b8f0fbef9b9b78367c/ompi_jenkins.log) | :question: UNKNOWN

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 14-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/7f7de5aca0fb198a705d2d45100c4045/raw/e057c4c201b042d2f0a1be0e02cc9abce5ce41bf/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 14-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/355de2678839a3cabd87452a2c147cbd/raw/e057c4c201b042d2f0a1be0e02cc9abce5ce41bf/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 19-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/b70d1c56f340f12b5dc282ab17e2bdc8/raw/e057c4c201b042d2f0a1be0e02cc9abce5ce41bf/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 19-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/27e4a10fc254dcba70e8e40f5ddb650d/raw/e057c4c201b042d2f0a1be0e02cc9abce5ce41bf/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the artefacts will be deleted after 19-Nov-2019

Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/5ef0c6e6998dadee479a2e885fd77c7c/raw/e057c4c201b042d2f0a1be0e02cc9abce5ce41bf/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>



Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/b22283ac79cacdb6bcc9a92a00919f6b/raw/e057c4c201b042d2f0a1be0e02cc9abce5ce41bf/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>



Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/846535ea979761fa960ddda23867a1dd/raw/79000216339f069434fed521383084fe1d10cbf6/ompi_jenkins.log) | :x: FAIL

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>



Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/ed1eac1efbbc5824ceba03828fb81140/raw/23c9e7f1407351ff6ddb1aeebbf8675c6334f092/ompi_jenkins.log) | :question: UNKNOWN

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>



Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/f257595c3391f266157241b8c8472097/raw/2d5b72c6c80510b386669549845f7542d5a4dfeb/ompi_jenkins.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>



Artefact file | Status
-- | --
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/21e77da6bdee84e06ea7db2188173c52/raw/4b7910dbee09ae0fcb0c49bd4853603c3dd8d5fb/ompi_jenkins.log) | :question: UNKNOWN

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>



Artefact file | Status
-- | --
[file2.log](https://gist.githubusercontent.com/mellanox-github/89ba1a1a5ba99295879bc70b87747840/raw/dc513f36adf8e05b1c4c150546f7072e3fe42fd5/file2.log) | :x: FAIL
[file.log](https://gist.githubusercontent.com/mellanox-github/89ba1a1a5ba99295879bc70b87747840/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file.log) | :heavy_check_mark: PASS
[coverity_report_new3.tar.bz2](https://gist.githubusercontent.com/mellanox-github/89ba1a1a5ba99295879bc70b87747840/raw/ea0cad6abdd2a2a6625d50e4523e8bef1ca2f634/coverity_report_new3.tar.bz2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>



Artefact file | Status
-- | --
[coverity_report_new3.tar.bz2](https://gist.githubusercontent.com/mellanox-github/4ed8796f819a856c5727c38e3188c1e8/raw/ea0cad6abdd2a2a6625d50e4523e8bef1ca2f634/coverity_report_new3.tar.bz2) | :question: 
[file2.log](https://gist.githubusercontent.com/mellanox-github/4ed8796f819a856c5727c38e3188c1e8/raw/dc513f36adf8e05b1c4c150546f7072e3fe42fd5/file2.log) | :x: FAIL
[file.log](https://gist.githubusercontent.com/mellanox-github/4ed8796f819a856c5727c38e3188c1e8/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b></b> (click for details)</summary>



Artefact file | Status
-- | --
[coverity_report_new3.tar.bz2](https://gist.githubusercontent.com/mellanox-github/8f4b84ac42e825693951e8ee611e214a/raw/ea0cad6abdd2a2a6625d50e4523e8bef1ca2f634/coverity_report_new3.tar.bz2) | :question: 
[file.log](https://gist.githubusercontent.com/mellanox-github/8f4b84ac42e825693951e8ee611e214a/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file.log) | :heavy_check_mark: PASS
[file2.log](https://gist.githubusercontent.com/mellanox-github/8f4b84ac42e825693951e8ee611e214a/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file2.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>



Artefact file | Status
-- | --
[coverity_report_new3.tar.bz2](https://gist.githubusercontent.com/mellanox-github/21dc297b326d8d7c84835aadc234655f/raw/ea0cad6abdd2a2a6625d50e4523e8bef1ca2f634/coverity_report_new3.tar.bz2) | :question: 
[file.log](https://gist.githubusercontent.com/mellanox-github/21dc297b326d8d7c84835aadc234655f/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file.log) | :heavy_check_mark: PASS
[file2.log](https://gist.githubusercontent.com/mellanox-github/21dc297b326d8d7c84835aadc234655f/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file2.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>



Artefact file | Status
-- | --
[coverity_report_new3.tar.bz2](https://gist.githubusercontent.com/mellanox-github/94c732e61893a1022d944d48e0aa89ae/raw/ea0cad6abdd2a2a6625d50e4523e8bef1ca2f634/coverity_report_new3.tar.bz2) | :question: 
[file2.log](https://gist.githubusercontent.com/mellanox-github/94c732e61893a1022d944d48e0aa89ae/raw/dc513f36adf8e05b1c4c150546f7072e3fe42fd5/file2.log) | :x: FAIL
[file.log](https://gist.githubusercontent.com/mellanox-github/94c732e61893a1022d944d48e0aa89ae/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>



Artefact file | Status
-- | --
[coverity_report_new3.tar.bz2](https://gist.githubusercontent.com/mellanox-github/c90f4ebcd544b466adf3501218e85dc6/raw/ea0cad6abdd2a2a6625d50e4523e8bef1ca2f634/coverity_report_new3.tar.bz2) | :question: 
[file.log](https://gist.githubusercontent.com/mellanox-github/c90f4ebcd544b466adf3501218e85dc6/raw/1ae37253220af9575dbb3bfcc3b25a6aa4bf4757/file.log) | :heavy_check_mark: PASS
[file2.log](https://gist.githubusercontent.com/mellanox-github/c90f4ebcd544b466adf3501218e85dc6/raw/75337d1d7ec96b5370314b66af256a82e14e8ddb/file2.log) | :question: UNKNOWN

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>



Artefact file | Status
-- | --
[coverity_report.tar.bz2](https://gist.githubusercontent.com/mellanox-github/9bec674214aca2dc26506ad69cc95fbb/raw/6c66ec5f96ae7c39938b3dc48cfffef28d7e0f5f/coverity_report.tar.bz2) | :question: 
[ompi_jenkins.log](https://gist.githubusercontent.com/mellanox-github/9bec674214aca2dc26506ad69cc95fbb/raw/79a4092fdc5417a135efb9c79918dd4b2caade08/ompi_jenkins.log) | :heavy_check_mark: PASS

**Pull request closed without merging**
